# Dockerfile for MLflow Server
FROM python:3.10-slim

WORKDIR /mlflow

RUN pip install --no-cache-dir mlflow psycopg2-binary

# Create necessary directories
RUN mkdir -p /mlflow/data /mlflow/artifacts

EXPOSE 5000

CMD ["mlflow", "server", "--host", "0.0.0.0"]
